sudo: false
language: scala
jdk:
  - oraclejdk8
scala:
  - 2.10.6
  - 2.11.11
  - 2.12.3

before_install:
  - if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      openssl aes-256-cbc -K $encrypted_5a2f424f5ae3_key -iv $encrypted_5a2f424f5ae3_iv -in .travis/secrets.tar.enc -out .travis/secrets.tar -d;
      tar xv -C .travis -f .travis/secrets.tar;
    fi
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test
after_success:
  - if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      sbt ++$TRAVIS_SCALA_VERSION releaseEarly;
    fi
before_deploy:
  - ls -la .travis
deploy:
  skip_cleanup: true
  provider: script
  script:
    - ls -la .travis
  on:
    tags: true

env:
  global:
    - secure: nRuiXMT1ZDdS3nyBEBF0nhERnvoiHPTfloK4jEML/+Ip+P/ynA4/u52O9bk+REBSWA0OPhS1Yb+s73o3/OE0byGOh+lHObjQy1Jpgbxot7vS4gRYBAbQJPC/VnkzuBL/Mskg9oYyFF2ic6V1IGIHpsDUNzB8EwxAihXgXLg/RC+XCPcRvjhjPN52KX5qRVCba4l9CFCQ+ewu1edqjqhMJX/8lTGDbtzSUYsz6A0dE2qF8RqermfsNLeJ8Tx1ItzQISR2mcFdHTPIbMJ1H/wHjF//7y8V8NMhPIg4oPYmTo56q3PNWhhXdpEMMZeTLGPtBXsP01NVzPKGIaMyRb0bBXZJQ53xLXY+lF5nmgGOIQ4FwNbLgeejlic7yHor/VdIKKecVUm+mcyni6NjeOcvgk9U6Ut0To4EUeXJHwiNbVWH6n8xu7ipYf87GYOaHmwDwiQiDaCh0o+JvPsmuZeFmnMBD6r0Uz/BDictjYfnkwz9gkn7jEtDQ+L6cNkzaSNTtZaY73o1CRajNz7G9I54I7PqdkZNt0VDwLADTTOWCXpI7j6/lapHoYendcJS2g6Mb6huc1Ur/flIO1N2Gr67/tj5l9ub18VdlyNPnnCN2XYgrbtbM/Ak1+waz5xGEsnVHqPqXK4yat7Zg2hfe5f6bJ3DkAcQLdKGtCtpKQntQHI=
    - secure: XOYDk1gCRnbKGJ4nIi5Nhyst6Mf14wFoOvAsY64aXOCnYEdWvjMx567aU8NQCe6lp74LmORB/YMpolMPfEk9ektQKjam8p/U3d2GEC/0PB8xCs574S6ph+PCwGAee6Ld4v3GZjAx85ctWLebX0Uko7K20+WVpsC8NH8KtllEBW7uT7gb9qcA5t6XRMKtCBmTJ8HFlt8qMJIcYrbO1m8Gg7umqfxbHcEZ4Wcvbg44FVboT7mARHtcDR7zPURBPULx7OreFSaEsDZA3VpDYzBxo1G/UFYQHkQ9DE+JfPLN8rxjiheHIsUBzSr93Pdy31W2wA8A925VgcWtdiCSlaDHp/XwY6RzOpStWGmAPAOhSsp18wQBCI1LehxZh9zA5F3xZpWS1JYzmQ7YpB2cgr2aXaqzOwcVmhmFa3raXKQQ7YF7QoS2YhRUdiKNtbnSpuQlLE6H1TH5CMuzhIX3y5VgYKB/TTZxU+vLI6yX5MltVETX8KadRyxwjYY6MFNa6iR4bhYGSL5+uNWTyVutNqJ27ULOIpR/Sq1krYPDXIPKejbiw+dAX9v0VS6evCmncAk+t/f4JsMAvQqcpSGCEZlbcIdoqVodok4c7rA/WFWD6R0Cj75PcRJbJASS2HJLDKxQwJI1IzDIqBXQ+USRdfTqB2xKXN6HC+CSl2AeAHBH/9A=
    - secure: Xpg40LmP7f+RH8NX6VJXc8ia6TYEtYccxoc/gBFHAcJ4hOwoy4Khl1lUY9GqZpvL08xFpNJ+pFriWoYxSy+IaLKbxZLY6yk+iIlP9ki+MKeVSIdGfrO9qJSsLhd2DxhxHQKtF5F5OnglU+L3eJ1w69qZumNMxuCF2LT98W4wyg2cxoUcNW31zgz/NOJw3jU6U93IhKwOYb1SYBL1wsa9ZsTVtE/DiizDM+dftHLcFEuymJjtsMKtbxBTikAqB8tccIlBiQIrl9XRvb1qjtdDCm/9HqfmsV5eiBP7PP+TurtoYMgRUaToRgz80HNI4hSbaXHa941mSFWxAf7vIDAjCc8jDbobXZIwJ7+CC0wKQyjzzMx5uUiiMb1DpcEejv+8pXFMAlSo8VcmjWKIyaABp+eId3+v2UcEoJwhCi4lDZgXPSNzLu3cFV0E8wzJH0JdXQc+2m5KA9qI/KQXuFdPM/QTLj+dkqsnyX7qyE0wsBnWm7mQ49cK6ySS7GWZkEoeGf2wlfiXg6EptLk2dmls1ogahcDXixp59OeW6LK61RZGs07KQCHPl9idN5k17Kw/29P0ICkMU9NEqE1doAvQI114FtwJZYyDFVucCp4grFGjzS3Kj0c3BYhQFHv9UazAhbDv3LDC2r2jOFpxEuaHdOPX8XU7Sd1r0nv2s6+lbRM=
