sudo: false
language: scala
jdk:
  - oraclejdk8
scala:
  - 2.10.6
  - 2.11.11
  - 2.12.3

before_install:
  - if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      openssl aes-256-cbc -K $encrypted_5a2f424f5ae3_key -iv $encrypted_5a2f424f5ae3_iv -in .travis/secrets.tar.enc -out .travis/secrets.tar -d;
      tar xv -C .travis -f .travis/secrets.tar;
    fi
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test
after_success:
  - if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      sbt ++$TRAVIS_SCALA_VERSION releaseEarly;
    fi
deploy:
  on:
    tags: true

env:
  global:
    - secure: jcs8HlbwQtrUpANunkoyHMpRGqmAbEIhRWAiae/m8TRqLqxxuE8zahcQYdnYhhPEBEgNPOBe3sN1FTjbthSHoCMZkqUx+58q995YwtdYgpcZfD0yOCamdLBkLzBnUsCUR53XpZHZFMwnufl47M+voMDYp4Qhk6C+QEknpwVBBKx67DfIzzhAgkk9Xe+0HQts5TYbp3NaEDqhcflQJx0qoohlZsqH9vxaJH1VCh6oI2y6L9s4j4WH+08kP0ERR7goBWeabCCXgPX8rTab66Vlvx+zAooTks1CnRX0/CrG/6/LTxavC4jOlcP/alX1f4OlUxhB/COxs+V0dLL8FJYyLfdH6auMhCjYty3T2mbpn2VjF7uP1hxTwimNfDs5dKJ1s0DkoOzXFIz/LtvHaJe/QYeE86rnvzFUIegoJalONqWcn3NHpRqvzT3eS72Q/E6AbSzHx8UCy3NXARY67zIqCoAHOIuQ6R2zeLARc6hii3OZu0txb6l3UvYlcnp8fzT8mqbW6zzCOCmeqXIlZK+gEhCdxmeG/3aeC0WYmC/2kPWTiBhnwFEWK5EtSVnEdUO/621Yr/wiGCTBiV3hb+ucgs3oeFLktBdrfesU8Nfu745mgfOz1kNrvH0dudkztzU1tO9OPV8K0Xs6ClhlAPZEJ/VThMbi2SSyXx5zTZdJMH4=
    - secure: MtaVYJ13LR/0oMPttk9uEq/kHSyseLYop+5t1LThV7NvrGggO3RPj7mKzXplUFlw335w8aLkOqXjj6bhpxmigA8xendnkDJFvcpa/m2arGdKVcsLoshZQPLR2cngU/aWxq933rfZiUmaNVK+L4I6uulPUQ2+/SGVpSFrEhamCf84Vm491cdRH2WfVlJRrxQgntOmrbO6xSIVoLiyHeOaX+JCS7u3pNNilxxKGOAHKl6MK74ZOuyyIw7BikpUUI7CJ/vvKTvcVEiBAS655wowf37alC9zdfaV4S3DJKvtENxfG7xqhRTlR6o+JThpoMwZn4YMTyPJ4icmBuMKhkXTzYk/ho4aH8GN9tl68ZXGam5YuG3/gycnRuDJfeFm3WXTs2sqnNBZrbPuDMPfdE5ekLqvI2rgYs8XLu43bixKusPoQOdLzIgSmwHv4zp6CDMdYcEnvR9I9quMauXudf3ohSgU6Ulaa4jrJ10wDEcy/5kt8KDB47W5BEzX9Xl4682weTxOs5G7rwRlxsoZnAqTZTfeCsABWzCOCfzKEWq/j95yFk1A0wcYIXCWGx1JZpYz3EnvLwnakrHb1qvQm5qRlR7T1MEtYgd3XcQ0CEX+1RiBEULvgFE7g0fgcFrpKXL54YNddlbJPqu1wEv2tUetFvff6+anFPZwSwofEBx7ZA0=
    - secure: c8V16jGuymZrKMBYjTaD9EzwOMzKhgWO7XTFs2NNjqXx/Y7naI6yP/bbHGKBCYdW/QK8rdUFCHcfd6OVlvGnIqG6olZ2x0r52UFYr62kd0F7MeqVJRxD7KNlV70HUpi9jGrV75ebLThyaK9x1X19knN8Y46b9Zbsn7P/xfKdI40gaeOQ8Cb8B3d39gSntO9dPabidXkgn10PXI+YiwQ8H7Hof9YGpihnDwwzLrNjugFDmCwq7SianRjP310FAFeQu9ogdw6uX+Nj7B0ZGsQ1HopRsTnCrIgoNSYpYYK+kR8kzUp3SabCJuoiR2zMpGsuiyh+zxBkkdr4VFLE8fMZxA3U3EUzuJKPGHSp+/xxKWiblDAtnSKSBhMh1aMWqY6RUjq3RAQoRk5hduVm1NcVMa6P/q0JVsveP3/0IXhmwudabW/jDxwTSFvHcpGaVEb8rvmY+sLgUpnZcSYXy6eeFPjaGFUi7DXVZFOTbgGsvx37oPKxXhmcliICfiH9oaaBW29/9bNDt+aFe+Q53j3BhU7YP6G1KzYALX5GDQpUddGAZYrmDMZOgveI+oroxUuF62p9EsKI8gBBwEIpJtXPJ+ubdi2CdCaW6adcN5FleBz8eVNj9kg5qiFHWtTzu1o6HSLo469caUSBLNw3XJa4ivX2kowzti+4ooxXd5/ZOq4=
