sudo: false
language: scala
jdk:
  - oraclejdk8
scala:
  - 2.10.6
  - 2.11.11
  - 2.12.3

before_install:
  - if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      openssl aes-256-cbc -K $encrypted_5a2f424f5ae3_key -iv $encrypted_5a2f424f5ae3_iv -in .travis/secrets.tar.enc -out .travis/secrets.tar -d;
      tar xv -C .travis -f .travis/secrets.tar;
    fi
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test
after_success:
  - if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      sbt ++$TRAVIS_SCALA_VERSION releaseEarly;
    fi
deploy:
  on:
    tags: true

env:
  global:
    - secure: TAs5tEAB+LZ0ZSbPoOpRmrp8n7sRgtohHCg9UpMYA/qnSmh+XR/rVPWQUAFLR2WISj7HqfgHX2WBnjVhT7GEYiL+T45Bcf62exsduauqj/+1aJhyIPLAbXJnwPPZjnEXMQ4GaBKHO33nugEtAK17ZeeCcUgpSKj8WRFMe2Xf2gjSlqkbTBZQF4MbF+sqaJqCsVASuRh+XKvTgSZzdF7w2PBTh9eG1QKWSTNFvA6MRmAyiBnJSefwBbbb/m22lpexPFgzY7iW1vJORPlxdSbBXVAgUBjTo94D22WXWDlBf4Ut6ybfi2u85vja2ZqhkOAdU0dCIOHRcJ30DXEEwdvZUpN9jo4QIHHSONpo0FHTUaJdd6T2NFQAG06Dazlscglmpps4XuM4MLaT/YKyGhrXb4f0kT18ACMIUXLRQZtfAx/lTUr7BZtV13W11cHouGVp8OdmacrjzIGvzRhbV4uFv/vxO9bVvfTajiy+8HG8OyzO0CoqsqLHqo9qV/SdhFLViR0+a5G/eqDCFH6GUJo8ZgNxYv+tqwPZ+wyaj/9Gm1JlIYJmCA9VPr1hdxc+uDz9UPHZ2dwRsx0mEjL00TW1zLq2bPY3rIocWW5me4c98GMldzXYtQKCsDNS/AAuqVBCfA+wEJrPlZ0DU5lBc3qZCGRCCY+YDTPn/gxGvcrF/UU=
    - secure: lxSW0w4hNJyNbuw2a9duw/5vEQZNpHTGpW7Carx9OvgXQAREa7ebi3Wxy7FgAzvK0krpN0S74eIUh/XM81fa4RU0GytHUuEFTJ6idCwohfr2v/A4d6DEXPWfXpyO4pkI5zn/9m2hoJQ0+9oKmW5guptLJaYgNQX/gmfB/YHcgmyaAX+Zf538ayfaUVcztHpiIqD/id5KS32tCKN3CCqQPoZthDiGAmybQdMyGGZAu4tM2bDhi4D49vdKKzIkH/y+gSR/wsc5ZQr+oiaIkNX5+Tk+yGoXeJl2WiZpYCvom0OsyEqhwQ6x1E4L4xTQd+VZ8dmMs6vlllDXn4JWEdafzV/Lh2S6zc14V2+jBnf01xtDzeucjpDH9EgX5/DZrKMxqAYB0uIIfLQmGG/5ADk/bfu9+mlX5WxcojicCtSCMWZJf4WYPNvhNrheVG+87R5KuXUEx0qED4BlIWmmSsYg75T1rfxqCM8EooVlLjRAISmk/mt3Jd+oZxLUH8vNg2ci/Q90VXmTQI7fAxBYoDtriuXA5sEBSfRisU+150RLCgOswEZMMP6KozeruU4MSp+yumcokS6aRN4ehcGHlPxemzIeYuCIMqxXgaaGNqAmqs7izBIk6+Mi21M5U3kqzKXEuciW3HHvwvloSzJH0BYrWDwYOEMblmzQjGsd4fbHrpM=
    - secure: POX0knW9x+adkR1gRto707YRO+kMn7KFhnS5KFhMcJQmMEqKoI4ww/8jtM+T1bf1k08PnVote6TQgpP169pRSf9rPAgcABOrPrc4Sc8CoSK01bRNmHkjfogAS3B4V/6PpKzdaTlvKbB2XQ2Q7P9481L6kyHfpb6oMl9PzPVMYfIVLtlKjnK74VcOLNyY7t0gVBt80j/EGh/gRR3dL8zEhzZ+KypIk66A1ehAHFbS9jQKzqy0R/NTeb2VSg73jv8dQ3jXW5/GKnwkV/XfPQo00RQp+WapNiJGuApaDfCGIWZ2XdNXOqSJm4gjt7j0P3AN8caFD4oxQ+RccZ/bXSUIP8HVtFX/wfZ4DrAlhsQWGfn9KVCL77waw1qY0E7CVU+7tkE7VYmHnvMlgNDHjutSlsNfpKjXzUh0fSXS932NaFBVE8iDpDjHEd4sjyrtmJ1FE1Diu/p50oR4wgsxsKTr2s2Rgvchx/e7mUYmnxRR0kgxDMof/M8MGUYow2Mm3gFhBYzBw5U6yd52C6LjAPIs/cShRjb3tplUGSK2rQqXYfRxD0IhRLBkUStlcqWs6mjkClSg0aFH1IZaxg27a8xdCz3UuDwcyBEtGCMPsD2lhh6hHELlYpr3/80eIJcl8hHrxwhmsxctc9rfY+GUlY/m0U3aqp1bZT36TBIZ/DHrWvA=
